target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'core', :path => '../core'
  pod 'SDWebImageSwiftUI'
  pod 'KMPNativeCoroutinesAsync'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
