target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'core', :path => '../core'
  pod 'KMPNativeCoroutinesCombine'  # Combine implementation
  pod 'SDWebImageSwiftUI'
  pod 'lottie-ios'
  pod 'KMPNativeCoroutinesAsync' 
end
