target 'MangaKu' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'SDWebImageSwiftUI'
  pod 'KMPNativeCoroutinesAsync', '~> 1.0.0-ALPHA-4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
